#+TITLE: Video conferencing and Remote Learning at the MCMP
#+AUTHOR: Conrad Friedrich

These comments are hopefully helpful to those people at the MCMP planning to do some academic philosophy remotely. Because needs vary, I tried to summarize the comments under a number of different use-cases. Feel free to contact me for changes and additions at (conrad.friedrich at lmu dot de)[fn:1].

* Video call 
Recommendation: Jitsi Meet

https://meet.lrz.de

Recommended (by LMU IT) number of participants up to 15 

** Features
- Free and open source (FOSS) software.
- Hosted by the LRZ (IT department of the LMU) in Germany. 
- No setup required. 
- No account required (except host).
- Runs directly in the browser (Chrome, Firefox), additionally iOS and Android apps.
- Video/audio conferencing, screen sharing, no whiteboard.
- Moderating: muting users, 'raising hand' feature, chat.
- Security: passwords for session (has to be activated manually, slightly hidden), no end-to-end encryption.
- Easily shareable URLs consisting of four random words.
- No scheduling
- New participants can be set to muted and without video upon joining.

** Recommendations
- Mute yourself with ~M~ and unmute temporarily by holding ~SPACE~.
- Set a password! Using the browser on main screen click the small (i) in the button right and 'add password'.

* Workshop / Colloquia 
Recommendation: Zoom meetings

https://lmu-munich.zoom.us/

Up to 300 participants

Regulations apply.[fn:2]

** Features
- Free through LMU (or a private account up to 100 participants).
- Proprietary software.
- Server location unrestricted.
- Requires installation of App (Windows, Mac, Linux, iOS, Android) or browser-extension.
- No Account required (except host).
- Video/audio conferencing, screen sharing, whiteboard.
- Moderating: mutings users, chat.
- Security: passwords for meetings, waiting room for new participants to prevent 'zoom bombing', general data privacy concerns because of lax US laws, no end-to-end-decryption.
- Scheduling of events

** Recommendations:
- Always set a password for your meeting! Share the password through external channels (like mail).
The LMU IT in addition recommends the following settings for meetings:[fn:3]
- Deactivate file transfer
- Deactivate participant feedback function 
- Allow virtual background

** Using Zoom's whiteboard function with a tablet


* Seminar / Classroom
Recommendation: Zoom meetings or Zoom webinars.

https://lmu-munich.zoom.us/

Up to 300 participants

** Features (meeting)
Just as described above.

As in the case of a presentation, the classroom works well as a zoom meeting, however, depending on the number of participants, a bit more features might be helpful, to avoid disturbances during the class. In particular, you can disable participants to share their screen, or share video or audio at all. Communication can proceed through the chat function or after  
** Features (webinars)
- Quite expensive, only limited licenses through LMU. If we have need for it, we can apply for it at the LMU IT.
- More geared towards teacher-centered teaching than meetings.
- Moderating: muting users, chat, 'raising hand', only selected participants ('panelists') can share screen, video. Everyone can share audio, if allowed. Host and moderator can be distinct.

* Lectures
Recommendation: VideoOnline or LMUCast

https://videoonline.edu.lmu.de, https://cast.itunes.uni-muenchen.de/#/home

Here, lectures are prerecorded, and the students can follow them at home, with additional interactions through message boards etc. The LMU offers an optional service to film the lectures in a lecture hall. If there is any need for this type of teaching, I'm happy to assist in coordinating with the LMU.

* FAQ
** Why these and not alternatives? Google Meet, Skype etc.
The LMU IT has expressed but did not specify concerns with Skype and Facetime for privacy reasons.[fn:4] The wording makes it sound like the use of these systems for teaching is prohibited. I wonder what makes Zoom a better tool than Skype or Facetime, privacy-wise.

Adobe Connect (as per LMU via DNF Conf) requires ~Adobe Flash Player~! lol.
** Aren't there security concerns with Zoom?
There are, and it's important to stay on top of things. At the moment, I think as long as some precautions are met (like setting a password for your meeting), the benefits outweigh the risks involved. For a review, see [[https://www.cs.columbia.edu/~smb/blog/2020-04/2020-04-06.html][Steven Bellovin (Columbia) write about this]]. See [[https://blogs.harvard.edu/doc/2020/03/27/zoom][Doc Searls]] for a critical stance on some of Zoom's privacy issues. 

* TODO Describe the graphical tablet and how to install on macOS 
* TODO Evaluate need for webinars 

* Footnotes

[fn:1] Or for the technically minded, post a pull request for this repository.

[fn:2] https://www.it-servicedesk.uni-muenchen.de/it-angebote/zoom/nutzung_datenschutz/index.html

[fn:3] https://www.itg.uni-muenchen.de/service/zoom/index.html

[fn:4] https://www.itg.uni-muenchen.de/service/zoom/index.html
