#+TITLE: Video conferencing and Remote Learning at the MCMP
#+AUTHOR: Conrad Friedrich

These comments are hopefully helpful to those people at the MCMP planning to do some academic philosophy and to teach remotely. These comments are very much work in progress. We're thankful for questions or changes and additions. Contact: (conrad.friedrich at lmu dot de)[fn:1]. 

The LMU has approved of some conferencing software described below but *disallowed the use of Skype, Facetime* and similar for teaching and official communication.[fn:2]

* For Video Calls, Workshops, Colloquia, Seminars, Classrooms, ...
Recommendation: Zoom meetings

https://lmu-munich.zoom.us/

Up to 300 participants

Regulations apply.[fn:3]

For almost all use cases, we recommend using Zoom meetings. It promises to be reliable, easy-to-use, and to have enough features to accommodate most academic needs. Using a one-stop solution comes with the additional benefit that e.g. students only have be familiar with one software package in order to take part in the classes. 

To start using Zoom, follow the link above and login with your lmu credentials. You'll be able to schedule and start meetings as well as change your settings there. The Zoom account through LMU has a couple of advantages over the free 'basic' Zoom account. 

** TODO Workout advantages of LMU account.

** Using Zoom: Example
Let's consider a use case similar to [[https://www.youtube.com/watch?v=HCo5ZX0G5ls][this video by Eric Pacuit]]. We'd like to show a presentation and annotate the slides by hand. To do so, open the slides you want to present in your favorite software. In a Zoom meeting, choose 'Share Screen' and choose your presentation software in the following dialogue (for example Preview for slides in pdf format on macOS). Participants can now follow the slides of your presentation. In the Zoom toolbar, you can choose 'Annotate' and then 'Draw' to annotate your slides with your input device. Alternatively, you can use the annotation feature of your presentation software, if it has it (e.g. Preview for macOS offers annotations). With a mouse, this works tolerable, but you might achieve better results with a graphic tablet that simulates writing with pen and paper digitally. We bought a small batch of ~XP-Pen Star G640~[fn:4] at the MCMP if you'd like to use one. If you need assistance setting it up, we're happy to help. It's probably a good idea to familiarize yourself with these features a bit before starting your class.

** Features
- Free through LMU.
- Requires installation of App (Windows, Mac, Linux, iOS, Android) or browser-extension.
- No Account required (except host).
- Scheduling of events
- Video/audio conferencing, screen sharing (e.g. for powerpoints), whiteboard.
- Moderating: mutings users, 'raising hand' feature, chat.
- Security: passwords for meetings, waiting room for new participants to prevent 'zoom bombing', general data privacy concerns (see below), no end-to-end-decryption.
- Server location undisclosed
- Proprietary software.

** Recommendations:
- Since Zoom is in high demand at the moment, users might receive so-called phishing emails that might look official but contain links to fraudulent websites. Always verify the domain ends in ~zoom.us~ when you enter your credentials on a website.
- Always set a password for your meeting! Share the password through external channels (like mail).
- To increase performance and save bandwidth, consider deactivating video and audio streams of participants currently not talking.
The LMU IT in addition recommends the following settings for meetings:[fn:3]
- Deactivate file transfer
- Deactivate participant feedback function 
- Allow virtual background

* For Lectures
Recommendation: LMUCast

https://cast.itunes.uni-muenchen.de/

If you plan to do a larger lecture, the general plan is to prerecord them and the students then follow the lecture at home with additional interactions through message boards etc. The LMU offers an optional service to film the lectures in a lecture hall. If there is any need for this type of teaching, we're happy to assist in coordinating with the LMU.

* FAQ
** Why Zoom and not alternatives? Google Meet, Skype etc.
The LMU IT has expressed but did not specify concerns with Skype and Facetime for privacy reasons.[fn:2] 

| Product         | LMU's stance on it for use in remote teaching |
|-----------------+-----------------------------------------------|
| Jitsi Meet      | Recommended                                   |
| Zoom            | Recommended                                   |
| Adobe Connect   | Recommended[fn:5]                             |
| Microsoft Teams | Currently in evaluation                       |
| Skype           | Explicitly Disallowed                         |
| Facetime        | Explicitly Disallowed                         |
| Cisco WebEx     | None so far                                   |
| GoToMeeting     | None so far                                   |
| Google Hangouts | None so far                                   |

** TODO More information on the LMU's stance on different products.

** Aren't there security concerns with Zoom?
There are, and it's important to stay on top of things. At the moment, long as some precautions are met (like setting a password for your meeting), the benefits outweigh the risks involved. For a review, see [[https://www.cs.columbia.edu/~smb/blog/2020-04/2020-04-06.html][Steven Bellovin (Columbia) write about this]]. See [[https://blogs.harvard.edu/doc/2020/03/27/zoom][Doc Searls]] for a critical stance on some of Zoom's privacy issues. 
** What's with Zoom webinars?
- Quite expensive, only limited licenses through LMU. If we have need for it, we can apply for it at the LMU IT.
- More geared towards teacher-centered teaching than meetings.
- Has more features to moderate users if there are lots of disturbances.

* Alternative for Video Calls: Jitsi Meet

If you put particular emphasis on data protection and privacy, the LMU also recommends an alternative tool called Jitsi Meet.

https://meet.lrz.de

Recommended (by LMU IT) number of participants up to 15 

** Features
- Free and open source (FOSS) software.
- Hosted by the LRZ (IT department of the LMU) in Germany. 
- No setup required. 
- No account required (except host).
- Runs directly in the browser (Chrome, Firefox), additionally iOS and Android apps.
- Video/audio conferencing, screen sharing, no whiteboard.
- Moderating: muting users, 'raising hand' feature, chat.
- Security: passwords for session (has to be activated manually, slightly hidden), no end-to-end encryption.
- Easily shareable URLs consisting of four random words.
- No scheduling
- New participants can be set to muted and without video upon joining.

** Recommendations
- Mute yourself with ~M~ and unmute temporarily by holding ~SPACE~. (Push to talk - decreases noise levels during the call)
- Set a password! Using the browser on main screen click the small (i) in the button right and 'add password'.

* Footnotes

[fn:1] Or for the technically minded, post a pull request for [[https://github.com/conradfriedrich/remote-philosophy][this repository]].

[fn:2] https://www.itg.uni-muenchen.de/service/zoom/index.html

[fn:3] https://www.it-servicedesk.uni-muenchen.de/it-angebote/zoom/nutzung_datenschutz/index.html

[fn:4] Download the drivers at https://www.xp-pen.de/download-244.html.

[fn:5] ~Adobe Connect~ requires ~Adobe Flash Player~, which is outdated.
